name: Uptime Monitor
on:
  schedule:
    - cron: '*/60 *  * * *' #every 1 hour
    - cron: '*/3 *  * * *'
jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Uptime Check
    steps:
      - name: Ping Site
        uses: srt32/uptime@v0.2
        with:
          url-to-hit: 'https://www.wikipedia.org/'
          expected-statuses: '200'
